/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Unauthenticated liveness probe. Skipped by the auth middleware
         *     (see ``UNAUTHENTICATED_PATHS`` in ``src.auth.middleware``). DB
         *     connectivity is deliberately not checked here — pool_pre_ping
         *     recycles dead connections, and a health endpoint that depends on
         *     Postgres would false-positive during rolling restarts.
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Personas
         * @description Return stable synthetic identities for the current tenant's demo.
         */
        get: operations["listDemoPersonas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Report dependency state for the deploy gate; 503 if the API can't serve.
         */
        get: operations["readinessCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/audits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recommendation Audits
         * @description Return newest prediction audits visible inside the request tenant.
         */
        get: operations["listRecommendationAudits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catalog
         * @description Return deterministic local metadata with the persona's durable state overlay.
         */
        get: operations["listDemoCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Online User Features
         * @description Expose the tenant-keyed Redis-backed Feast read used by online ranking.
         */
        get: operations["getOnlineUserFeatures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History
         * @description Return recent interactions for the demo's watch-history panel.
         */
        get: operations["listRatingHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Library
         * @description Return one bounded keyset page plus counts for all Library tabs.
         */
        get: operations["listLibrary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/movies/{movie_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Movie Detail
         * @description Return persisted detail metadata and the persona's durable movie state.
         */
        get: operations["getMovieDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/movies/{movie_id}/dismissal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Dismissal */
        put: operations["dismissMovie"];
        post?: never;
        /** Delete Dismissal */
        delete: operations["undoMovieDismissal"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/movies/{movie_id}/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set State Rating */
        put: operations["setMovieStateRating"];
        post?: never;
        /** Delete State Rating */
        delete: operations["deleteMovieStateRating"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/movies/{movie_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Movie State
         * @description Return one selected persona's canonical live state for a movie.
         */
        get: operations["getMovieState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/movies/{movie_id}/watched": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Watched */
        put: operations["setMovieWatched"];
        post?: never;
        /** Remove From History */
        delete: operations["removeMovieFromHistory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/movies/{movie_id}/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Watchlist */
        put: operations["addMovieToWatchlist"];
        post?: never;
        /** Delete Watchlist */
        delete: operations["removeMovieFromWatchlist"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Reset Ratings
         * @description Compatibility bulk rating clear; watched history is preserved.
         */
        delete: operations["resetDemoRatings"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/ratings/{movie_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Rate Movie
         * @description Create or replace one rating for a tenant-scoped demo persona.
         */
        put: operations["setMovieRating"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recommendations
         * @description Run learned two-stage serving or an explicit popularity fallback.
         */
        get: operations["recommendMovies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/taste-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Taste Profile
         * @description Summarize live ratings without claiming deployed-model attribution.
         */
        get: operations["getLiveRatingsTasteSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whoami
         * @description Authenticated echo of the resolved identity.
         */
        get: operations["getCurrentActor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditPredictionItem */
        AuditPredictionItem: {
            /**
             * Candidate Source
             * @default unknown
             */
            candidate_source: string;
            /** Features */
            features: {
                [key: string]: number;
            };
            /** Movie Id */
            movie_id: number;
            /** Score */
            score: number;
            /** Seed Movie Id */
            seed_movie_id?: number | null;
        };
        /** CatalogItem */
        CatalogItem: {
            /** Genres */
            genres: string[];
            /** Interaction Count */
            interaction_count: number;
            /**
             * Metadata Source
             * @enum {string}
             */
            metadata_source: "reviewed-fixture" | "tmdb-snapshot" | "movielens";
            /** Movie Id */
            movie_id: number;
            /** Overview */
            overview: string | null;
            /** Poster Url */
            poster_url: string | null;
            /** Release Year */
            release_year: number | null;
            /**
             * Source Status
             * @enum {string}
             */
            source_status: "complete" | "partial" | "unavailable";
            state: components["schemas"]["MovieStateResponse"] | null;
            /** Title */
            title: string;
            /** Tmdb Id */
            tmdb_id: string | null;
        };
        /** CatalogPageInfo */
        CatalogPageInfo: {
            /** Has More */
            has_more: boolean;
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** CatalogResponse */
        CatalogResponse: {
            /** Items */
            items: components["schemas"]["CatalogItem"][];
            page: components["schemas"]["CatalogPageInfo"];
            /** Tenant Id */
            tenant_id: string;
            /** User Id */
            user_id: number;
        };
        /** CurrentActorResponse */
        CurrentActorResponse: {
            /** Authorized Party */
            authorized_party: string;
            /** Realm */
            realm: string;
            /** Redis Prefix */
            redis_prefix: string;
            /** Roles */
            roles: string[];
            /** Tenant Display Name */
            tenant_display_name: string;
            /** Tenant Id */
            tenant_id: string;
            /** User Id */
            user_id: string;
        };
        /** CursorPageResponse */
        CursorPageResponse: {
            /** Has More */
            has_more: boolean;
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            detail: string;
        };
        /** FeedbackMutationResponse */
        FeedbackMutationResponse: {
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "changed" | "no_change";
            /** Replayed */
            replayed: boolean;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            state: components["schemas"]["MovieStateResponse"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryItem */
        HistoryItem: {
            /** Genres */
            genres: string[];
            /** Movie Id */
            movie_id: number;
            /** Rating */
            rating: number | null;
            /** Timestamp */
            timestamp: number;
            /** Title */
            title: string;
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Items */
            items: components["schemas"]["HistoryItem"][];
            /** Tenant Id */
            tenant_id: string;
            /** User Id */
            user_id: number;
        };
        /** LibraryCountsResponse */
        LibraryCountsResponse: {
            /** History */
            history: number;
            /** Rated */
            rated: number;
            /** Watchlist */
            watchlist: number;
        };
        /** LibraryMovieResponse */
        LibraryMovieResponse: {
            /** Genres */
            genres: string[];
            /** Movie Id */
            movie_id: number;
            state: components["schemas"]["MovieStateResponse"];
            /** Title */
            title: string;
        };
        /** LibraryResponse */
        LibraryResponse: {
            counts: components["schemas"]["LibraryCountsResponse"];
            /** Items */
            items: components["schemas"]["LibraryMovieResponse"][];
            page: components["schemas"]["CursorPageResponse"];
            /** Query */
            query: string | null;
            /**
             * Sort
             * @enum {string}
             */
            sort: "recent" | "title" | "rating";
            /**
             * Tab
             * @enum {string}
             */
            tab: "rated" | "watchlist" | "history";
            /** Tenant Id */
            tenant_id: string;
            /** User Id */
            user_id: number;
        };
        /** MovieDetailResponse */
        MovieDetailResponse: {
            item: components["schemas"]["CatalogItem"];
            /** Tenant Id */
            tenant_id: string;
            /** User Id */
            user_id: number;
        };
        /** MovieStateResponse */
        MovieStateResponse: {
            /** Dismissed At */
            dismissed_at: string | null;
            /** Movie Id */
            movie_id: number;
            /** Rating */
            rating: number | null;
            /** Rating Updated At */
            rating_updated_at: string | null;
            /** Revision */
            revision: number;
            /** Tenant Id */
            tenant_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** User Id */
            user_id: number;
            /** Watched At */
            watched_at: string | null;
            /** Watchlisted At */
            watchlisted_at: string | null;
        };
        /** OnlineUserFeaturesResponse */
        OnlineUserFeaturesResponse: {
            /** Feature Timestamp */
            feature_timestamp: string;
            /** Source */
            source: string;
            /** Tenant Id */
            tenant_id: string;
            /** User Days Active */
            user_days_active: number | null;
            /** User Days Since Last Interaction */
            user_days_since_last_interaction: number | null;
            /** User Id */
            user_id: number;
            /** User Interaction Count */
            user_interaction_count: number | null;
        };
        /** PersonaItem */
        PersonaItem: {
            /** Description */
            description: string;
            /** Display Name */
            display_name: string;
            /** Slug */
            slug: string;
            /** User Id */
            user_id: number;
        };
        /** PersonaResponse */
        PersonaResponse: {
            /** Items */
            items: components["schemas"]["PersonaItem"][];
            /** Tenant Id */
            tenant_id: string;
        };
        /** RatingMutationResponse */
        RatingMutationResponse: {
            /** Changed */
            changed: number;
            /** Tenant Id */
            tenant_id: string;
            /** User Id */
            user_id: number;
        };
        /** RatingRequest */
        RatingRequest: {
            /** Rating */
            rating: number;
        };
        /**
         * ReadinessResponse
         * @description What a deploy gate reads off ``/readyz``.
         *
         *     ``database`` and ``jwks`` decide the status code because they are the
         *     dependencies this process cannot serve a single authenticated request
         *     without. The two sidecars are reported rather than gated — see the handler.
         */
        ReadinessResponse: {
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "error";
            /**
             * Feature Server
             * @enum {string}
             */
            feature_server: "ok" | "unavailable";
            /**
             * Jwks
             * @enum {string}
             */
            jwks: "ok" | "error";
            /**
             * Model Server
             * @enum {string}
             */
            model_server: "ok" | "unavailable";
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not-ready";
        };
        /** RecommendationAuditItem */
        RecommendationAuditItem: {
            /** Actor User Id */
            actor_user_id: string;
            /** Candidate Latency Ms */
            candidate_latency_ms: number;
            /** Candidate Sources */
            candidate_sources: {
                [key: string]: number;
            };
            /** Candidate Version */
            candidate_version: string;
            /** Correlation Id */
            correlation_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Endpoint */
            endpoint: string;
            /** Excluded Count */
            excluded_count: number;
            /** Exclusion Hash */
            exclusion_hash: string;
            /** Fallback Reason */
            fallback_reason: string | null;
            /** Feature Event Time */
            feature_event_time: string | null;
            /** Feature Latency Ms */
            feature_latency_ms: number;
            /** Feature Version */
            feature_version: string;
            /** Filter Policy */
            filter_policy: string;
            /** Http Status */
            http_status: number;
            /** Input State Hash */
            input_state_hash: string;
            /** Input State Revision */
            input_state_revision: number;
            /** Latency Ms */
            latency_ms: number;
            /** Model Latency Ms */
            model_latency_ms: number;
            /** Model Version */
            model_version: string;
            /** Outcome */
            outcome: string;
            /** Policy */
            policy: string;
            /** Positive Signal Count */
            positive_signal_count: number;
            /** Predictions */
            predictions: components["schemas"]["AuditPredictionItem"][];
            /** Ranker Latency Ms */
            ranker_latency_ms: number;
            /** Ranker Version */
            ranker_version: string;
            /** Reason */
            reason: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Tenant Id */
            tenant_id: string;
            /** User Id */
            user_id: number;
        };
        /** RecommendationAuditResponse */
        RecommendationAuditResponse: {
            /** Items */
            items: components["schemas"]["RecommendationAuditItem"][];
            /** Tenant Id */
            tenant_id: string;
            /** User Id */
            user_id: number;
        };
        /** RecommendationItem */
        RecommendationItem: {
            /** Genres */
            genres: string[];
            /**
             * Metadata Source
             * @enum {string}
             */
            metadata_source: "reviewed-fixture" | "tmdb-snapshot" | "movielens";
            /** Movie Id */
            movie_id: number;
            /** Overview */
            overview: string | null;
            /** Poster Url */
            poster_url: string | null;
            /** Reason */
            reason: string;
            /** Release Year */
            release_year: number | null;
            /** Score */
            score: number;
            /** Title */
            title: string;
            /** Tmdb Id */
            tmdb_id: string | null;
        };
        /** RecommendationResponse */
        RecommendationResponse: {
            /** Items */
            items: components["schemas"]["RecommendationItem"][];
            /** Model Version */
            model_version: string;
            /** Policy */
            policy: string;
            serving_policy: components["schemas"]["ServingPolicyResponse"];
            /** Tenant Id */
            tenant_id: string;
            /** User Id */
            user_id: number;
        };
        /**
         * ServingPolicyResponse
         * @description Machine-readable proof of which policy served this response.
         *
         *     ``positive_signal_count`` and ``threshold`` are what let a client show
         *     progress toward learned serving without guessing at the rule, and
         *     ``score_scale`` names what ``RecommendationItem.score`` actually is so it
         *     is never rendered as a probability or a match percentage (ADR 0012).
         */
        ServingPolicyResponse: {
            /** Excluded Count */
            excluded_count: number;
            /** Filter Policy */
            filter_policy: string;
            /** Learned */
            learned: boolean;
            /** Name */
            name: string;
            /** Positive Signal Count */
            positive_signal_count: number;
            /** Reason */
            reason: string;
            /** Score Scale */
            score_scale: string;
            /** Threshold */
            threshold: number;
        };
        /** TasteGenreResponse */
        TasteGenreResponse: {
            /** Average Rating */
            average_rating: number;
            /** Genre */
            genre: string;
            /** Rated Count */
            rated_count: number;
        };
        /** TasteSummaryResponse */
        TasteSummaryResponse: {
            /** Average Rating */
            average_rating: number | null;
            /** Explanation */
            explanation: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Rating Count */
            rating_count: number;
            /**
             * Source
             * @constant
             */
            source: "live-ratings-v1";
            /** Tenant Id */
            tenant_id: string;
            /** Top Genres */
            top_genres: components["schemas"]["TasteGenreResponse"][];
            /** User Id */
            user_id: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    listDemoPersonas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaResponse"];
                };
            };
            /** @description Request parameters are invalid or cursor does not match query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Requested persona or movie does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Idempotency, state revision, or transition conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    readinessCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description The database or the auth provider is unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    listRecommendationAudits: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationAuditResponse"];
                };
            };
            /** @description Request parameters are invalid or cursor does not match query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Requested persona or movie does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Idempotency, state revision, or transition conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listDemoCatalog: {
        parameters: {
            query?: {
                q?: string | null;
                genre?: string | null;
                year_from?: number | null;
                year_to?: number | null;
                sort?: "title" | "newest" | "popular";
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogResponse"];
                };
            };
            /** @description Cursor is invalid for this query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Demo persona was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Idempotency, state revision, or transition conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getOnlineUserFeatures: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnlineUserFeaturesResponse"];
                };
            };
            /** @description Request parameters are invalid or cursor does not match query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Requested persona or movie does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Idempotency, state revision, or transition conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listRatingHistory: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Request parameters are invalid or cursor does not match query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Requested persona or movie does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Idempotency, state revision, or transition conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listLibrary: {
        parameters: {
            query?: {
                tab?: "rated" | "watchlist" | "history";
                sort?: "recent" | "title" | "rating";
                limit?: number;
                cursor?: string | null;
                q?: string | null;
            };
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryResponse"];
                };
            };
            /** @description Request parameters are invalid or cursor does not match query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Requested persona or movie does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Idempotency, state revision, or transition conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMovieDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
                movie_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovieDetailResponse"];
                };
            };
            /** @description Request parameters are invalid or cursor does not match query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Movie or demo persona was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Idempotency, state revision, or transition conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    dismissMovie: {
        parameters: {
            query?: {
                expected_revision?: number | null;
            };
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                user_id: number;
                movie_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackMutationResponse"];
                };
            };
            /** @description Request parameters are invalid or cursor does not match query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Requested persona or movie does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Idempotency, state revision, or transition conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    undoMovieDismissal: {
        parameters: {
            query?: {
                expected_revision?: number | null;
            };
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                user_id: number;
                movie_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackMutationResponse"];
                };
            };
            /** @description Request parameters are invalid or cursor does not match query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Requested persona or movie does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Idempotency, state revision, or transition conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    setMovieStateRating: {
        parameters: {
            query?: {
                expected_revision?: number | null;
            };
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                user_id: number;
                movie_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RatingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackMutationResponse"];
                };
            };
            /** @description Request parameters are invalid or cursor does not match query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Requested persona or movie does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Idempotency, state revision, or transition conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteMovieStateRating: {
        parameters: {
            query?: {
                expected_revision?: number | null;
            };
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                user_id: number;
                movie_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackMutationResponse"];
                };
            };
            /** @description Request parameters are invalid or cursor does not match query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Requested persona or movie does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Idempotency, state revision, or transition conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMovieState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
                movie_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovieStateResponse"] | null;
                };
            };
            /** @description Request parameters are invalid or cursor does not match query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Requested persona or movie does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Idempotency, state revision, or transition conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    setMovieWatched: {
        parameters: {
            query?: {
                expected_revision?: number | null;
            };
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                user_id: number;
                movie_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackMutationResponse"];
                };
            };
            /** @description Request parameters are invalid or cursor does not match query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Requested persona or movie does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Idempotency, state revision, or transition conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    removeMovieFromHistory: {
        parameters: {
            query?: {
                expected_revision?: number | null;
            };
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                user_id: number;
                movie_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackMutationResponse"];
                };
            };
            /** @description Request parameters are invalid or cursor does not match query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Requested persona or movie does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Idempotency, state revision, or transition conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    addMovieToWatchlist: {
        parameters: {
            query?: {
                expected_revision?: number | null;
            };
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                user_id: number;
                movie_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackMutationResponse"];
                };
            };
            /** @description Request parameters are invalid or cursor does not match query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Requested persona or movie does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Idempotency, state revision, or transition conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    removeMovieFromWatchlist: {
        parameters: {
            query?: {
                expected_revision?: number | null;
            };
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                user_id: number;
                movie_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackMutationResponse"];
                };
            };
            /** @description Request parameters are invalid or cursor does not match query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Requested persona or movie does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Idempotency, state revision, or transition conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    resetDemoRatings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingMutationResponse"];
                };
            };
            /** @description Request parameters are invalid or cursor does not match query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Requested persona or movie does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Idempotency, state revision, or transition conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    setMovieRating: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
                movie_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RatingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingMutationResponse"];
                };
            };
            /** @description Request parameters are invalid or cursor does not match query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Requested persona or movie does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Idempotency, state revision, or transition conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    recommendMovies: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Request parameters are invalid or cursor does not match query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Requested persona or movie does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Idempotency, state revision, or transition conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getLiveRatingsTasteSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TasteSummaryResponse"];
                };
            };
            /** @description Request parameters are invalid or cursor does not match query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Requested persona or movie does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Idempotency, state revision, or transition conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCurrentActor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentActorResponse"];
                };
            };
            /** @description Request parameters are invalid or cursor does not match query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Requested persona or movie does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Idempotency, state revision, or transition conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
