/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Unauthenticated liveness probe. Skipped by the auth middleware
         *     (see ``_UNAUTHENTICATED_PATHS`` in ``src.auth.middleware``). DB
         *     connectivity is deliberately not checked here — pool_pre_ping
         *     recycles dead connections, and a health endpoint that depends on
         *     Postgres would false-positive during rolling restarts.
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Personas
         * @description Return stable synthetic identities for the current tenant's demo.
         */
        get: operations["listDemoPersonas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/audits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recommendation Audits
         * @description Return newest prediction audits visible inside the request tenant.
         */
        get: operations["listRecommendationAudits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catalog
         * @description Return rateable movies and current ratings for one demo persona.
         */
        get: operations["listDemoCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Online User Features
         * @description Expose the tenant-keyed Redis-backed Feast read used by online ranking.
         */
        get: operations["getOnlineUserFeatures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History
         * @description Return recent interactions for the demo's watch-history panel.
         */
        get: operations["listRatingHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Reset Ratings
         * @description Clear a demo persona so the cold-start experience can be rebuilt.
         */
        delete: operations["resetDemoRatings"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/ratings/{movie_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Rate Movie
         * @description Create or replace one rating for a tenant-scoped demo persona.
         */
        put: operations["setMovieRating"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recommendations
         * @description Run learned two-stage serving or an explicit popularity fallback.
         */
        get: operations["recommendMovies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whoami
         * @description Authenticated echo of the resolved identity.
         */
        get: operations["getCurrentActor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditPredictionItem */
        AuditPredictionItem: {
            /** Features */
            features: {
                [key: string]: number;
            };
            /** Movie Id */
            movie_id: number;
            /** Score */
            score: number;
        };
        /** CatalogItem */
        CatalogItem: {
            /** Genres */
            genres: string[];
            /** Movie Id */
            movie_id: number;
            /** Rating */
            rating: number | null;
            /** Title */
            title: string;
        };
        /** CatalogResponse */
        CatalogResponse: {
            /** Items */
            items: components["schemas"]["CatalogItem"][];
            /** Tenant Id */
            tenant_id: string;
            /** User Id */
            user_id: number;
        };
        /** CurrentActorResponse */
        CurrentActorResponse: {
            /** Authorized Party */
            authorized_party: string;
            /** Realm */
            realm: string;
            /** Redis Prefix */
            redis_prefix: string;
            /** Roles */
            roles: string[];
            /** Tenant Display Name */
            tenant_display_name: string;
            /** Tenant Id */
            tenant_id: string;
            /** User Id */
            user_id: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryItem */
        HistoryItem: {
            /** Genres */
            genres: string[];
            /** Movie Id */
            movie_id: number;
            /** Rating */
            rating: number;
            /** Timestamp */
            timestamp: number;
            /** Title */
            title: string;
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Items */
            items: components["schemas"]["HistoryItem"][];
            /** Tenant Id */
            tenant_id: string;
            /** User Id */
            user_id: number;
        };
        /** OnlineUserFeaturesResponse */
        OnlineUserFeaturesResponse: {
            /** Feature Timestamp */
            feature_timestamp: string;
            /** Source */
            source: string;
            /** Tenant Id */
            tenant_id: string;
            /** User Days Active */
            user_days_active: number | null;
            /** User Days Since Last Interaction */
            user_days_since_last_interaction: number | null;
            /** User Id */
            user_id: number;
            /** User Interaction Count */
            user_interaction_count: number | null;
        };
        /** PersonaItem */
        PersonaItem: {
            /** Description */
            description: string;
            /** Display Name */
            display_name: string;
            /** Slug */
            slug: string;
            /** User Id */
            user_id: number;
        };
        /** PersonaResponse */
        PersonaResponse: {
            /** Items */
            items: components["schemas"]["PersonaItem"][];
            /** Tenant Id */
            tenant_id: string;
        };
        /** RatingMutationResponse */
        RatingMutationResponse: {
            /** Changed */
            changed: number;
            /** Tenant Id */
            tenant_id: string;
            /** User Id */
            user_id: number;
        };
        /** RatingRequest */
        RatingRequest: {
            /** Rating */
            rating: number;
        };
        /** RecommendationAuditItem */
        RecommendationAuditItem: {
            /** Actor User Id */
            actor_user_id: string;
            /** Candidate Latency Ms */
            candidate_latency_ms: number;
            /** Candidate Version */
            candidate_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Endpoint */
            endpoint: string;
            /** Fallback Reason */
            fallback_reason: string | null;
            /** Feature Latency Ms */
            feature_latency_ms: number;
            /** Feature Version */
            feature_version: string;
            /** Http Status */
            http_status: number;
            /** Latency Ms */
            latency_ms: number;
            /** Model Latency Ms */
            model_latency_ms: number;
            /** Model Version */
            model_version: string;
            /** Outcome */
            outcome: string;
            /** Policy */
            policy: string;
            /** Predictions */
            predictions: components["schemas"]["AuditPredictionItem"][];
            /** Ranker Latency Ms */
            ranker_latency_ms: number;
            /** Ranker Version */
            ranker_version: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Tenant Id */
            tenant_id: string;
            /** User Id */
            user_id: number;
        };
        /** RecommendationAuditResponse */
        RecommendationAuditResponse: {
            /** Items */
            items: components["schemas"]["RecommendationAuditItem"][];
            /** Tenant Id */
            tenant_id: string;
            /** User Id */
            user_id: number;
        };
        /** RecommendationItem */
        RecommendationItem: {
            /** Genres */
            genres: string[];
            /** Metadata Source */
            metadata_source: string;
            /** Movie Id */
            movie_id: number;
            /** Overview */
            overview: string | null;
            /** Poster Url */
            poster_url: string | null;
            /** Reason */
            reason: string;
            /** Release Year */
            release_year: number | null;
            /** Score */
            score: number;
            /** Title */
            title: string;
            /** Tmdb Id */
            tmdb_id: string | null;
        };
        /** RecommendationResponse */
        RecommendationResponse: {
            /** Items */
            items: components["schemas"]["RecommendationItem"][];
            /** Model Version */
            model_version: string;
            /** Policy */
            policy: string;
            /** Tenant Id */
            tenant_id: string;
            /** User Id */
            user_id: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    listDemoPersonas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listRecommendationAudits: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationAuditResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listDemoCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getOnlineUserFeatures: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnlineUserFeaturesResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listRatingHistory: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    resetDemoRatings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingMutationResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    setMovieRating: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
                movie_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RatingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingMutationResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    recommendMovies: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCurrentActor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentActorResponse"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated actor is not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request transaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
