#!/usr/bin/env bash
#
# Turn a stock Ubuntu 24.04 Hetzner CX22 into the box this project deploys to.
#
#   ssh root@<ip>
#   apt-get update && apt-get install --yes git
#   git clone https://github.com/kudratsingh/MovieLens-RecSys.git /opt/movielens
#   /opt/movielens/infra/host/bootstrap.sh "$(cat deploy-key.pub)"
#
# The public key argument is the one CI will deploy with (its private half goes
# into the `production` environment's DEPLOY_SSH_KEY secret). It can also be
# piped in with `-` as the argument, which is what avoids putting a key in the
# shell history of a box you do not fully trust yet.
#
# Every step is idempotent. That is not a nicety: this script is the only
# written record of how the box is configured, so it has to be re-runnable
# after a change to it -- otherwise the record and the box drift apart and the
# only way to reproduce the machine is to remember what was done by hand. Run
# it again after any edit; a second run should change nothing and say so.
#
# What it deliberately does NOT do:
#
#   * put secrets on the box. /opt/movielens/.env.prod is generated by hand
#     from infra/deploy/production.env.example and never lives in git, in an
#     image, or in this script;
#   * deploy anything. The first release is `infra/deploy/deploy.sh <sha>`,
#     which CI runs on every merge to main;
#   * configure DNS. Both public hostnames must already resolve to this box
#     before the first deploy, or the edge's ACME challenge fails.
set -euo pipefail

DEPLOY_USER=deploy
APP_DIR=/opt/movielens
HOST_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

# Set when any step actually restarts the Docker daemon, so the summary can say
# whether running containers were interrupted.
docker_restarted=no

usage() {
	cat <<'USAGE'
usage: bootstrap.sh [<ssh-public-key> | -]

  <ssh-public-key>  the deploy user's authorized key, quoted, e.g.
                    bootstrap.sh "$(cat deploy-key.pub)"
  -                 read the key from stdin instead
  (no argument)     allowed only when the deploy user already has an
                    authorized key; the SSH step is then skipped

Run as root on a stock Ubuntu 24.04 host. Safe to run repeatedly.
USAGE
}

step() { printf '\n== %s\n' "$1"; }
note() { printf '   %s\n' "$1"; }
die() {
	printf 'bootstrap: %s\n' "$1" >&2
	exit 1
}

# --- preconditions ----------------------------------------------------------

case "${1:-}" in
-h | --help)
	usage
	exit 0
	;;
esac

[ "$(id -u)" -eq 0 ] || die "run as root"

# The Docker apt repository is per-distribution and per-codename, and the sshd
# drop-in ordering below is Debian/Ubuntu's. Failing here beats half-applying.
# shellcheck disable=SC1091 # /etc/os-release is generated, not in the repo
. /etc/os-release
[ "${ID:-}" = "ubuntu" ] || die "expected Ubuntu, found ${ID:-unknown}"
: "${VERSION_CODENAME:?/etc/os-release carries no VERSION_CODENAME}"

ssh_key=""
case "${1:-}" in
"") : ;;
-) ssh_key="$(cat)" ;;
*) ssh_key="$1" ;;
esac

if [ -n "$ssh_key" ]; then
	case "$ssh_key" in
	ssh-ed25519\ * | ssh-rsa\ * | ecdsa-sha2-nistp*\ * | sk-ssh-ed25519*\ *) : ;;
	*) die "that does not look like an SSH public key (want the .pub half)" ;;
	esac
fi

export DEBIAN_FRONTEND=noninteractive

# --- the deploy user --------------------------------------------------------
# One unprivileged account owns the checkout, the secrets file and every
# container. CI authenticates as it and never as root: a compromised deploy key
# then costs this application rather than the machine.

step "deploy user"
if id -u "$DEPLOY_USER" >/dev/null 2>&1; then
	note "$DEPLOY_USER already exists"
else
	adduser --disabled-password --gecos "MovieLens deploy" "$DEPLOY_USER"
	note "created $DEPLOY_USER"
fi

deploy_home="$(getent passwd "$DEPLOY_USER" | cut -d: -f6)"
[ -n "$deploy_home" ] || die "cannot resolve $DEPLOY_USER's home directory"
authorized_keys="$deploy_home/.ssh/authorized_keys"

install -d -m 0700 -o "$DEPLOY_USER" -g "$DEPLOY_USER" "$deploy_home/.ssh"
touch "$authorized_keys"
chmod 0600 "$authorized_keys"
chown "$DEPLOY_USER:$DEPLOY_USER" "$authorized_keys"

if [ -n "$ssh_key" ]; then
	if grep -qxF "$ssh_key" "$authorized_keys"; then
		note "authorized key already present"
	else
		printf '%s\n' "$ssh_key" >>"$authorized_keys"
		note "added authorized key"
	fi
fi

# The lockout guard. Disabling password authentication a step below is
# irreversible from the outside if nothing can authenticate with a key, and a
# rebuilt box is a cheaper mistake to avoid here than to recover from.
[ -s "$authorized_keys" ] || die "$DEPLOY_USER has no authorized key; pass one as the argument"

# --- sshd -------------------------------------------------------------------

step "sshd: keys only"
# 01-, not 99-. Ubuntu's sshd_config puts `Include /etc/ssh/sshd_config.d/*.conf`
# at the very top and sshd takes the FIRST value it sees for a keyword, so a
# lower-numbered drop-in wins -- and Hetzner's images ship a cloud-init
# 50-cloud-init.conf that sets PasswordAuthentication yes. A 99- file would
# parse, apply nothing, and leave password logins open while looking closed.
cat >/etc/ssh/sshd_config.d/01-movielens.conf <<'SSHD'
# Managed by infra/host/bootstrap.sh. Edits here are overwritten on the next run.
PasswordAuthentication no
KbdInteractiveAuthentication no
PermitRootLogin prohibit-password
SSHD
chmod 0644 /etc/ssh/sshd_config.d/01-movielens.conf

sshd -t || die "sshd rejected the configuration; nothing was reloaded"

# Assert the effective value rather than trusting the file: sshd -T renders the
# whole include tree in precedence order, which is the only thing that answers
# "can somebody still log in with a password?"
effective_password_auth="$(sshd -T | awk '$1 == "passwordauthentication" { print $2 }')"
[ "$effective_password_auth" = "no" ] ||
	die "password authentication is still '$effective_password_auth'; check /etc/ssh/sshd_config.d/"

# Ubuntu 24.04 socket-activates sshd, so a reload may be a no-op there and the
# per-connection instances pick the config up on their own. Reload when there is
# a running service to reload, and never restart: restarting would be enough to
# drop the session running this script.
systemctl reload ssh 2>/dev/null || note "no running ssh.service to reload (socket-activated)"
note "password authentication off, root login by key only"

# --- firewall ---------------------------------------------------------------

step "firewall"
apt-get install --yes --no-install-recommends ufw >/dev/null
ufw --force default deny incoming >/dev/null
ufw --force default allow outgoing >/dev/null
for port in 22 80 443; do
	ufw allow "$port/tcp" >/dev/null
done
ufw --force enable >/dev/null
note "$(ufw status | tr '\n' ' ')"
# Worth knowing before it surprises somebody: ufw does not filter what Docker
# publishes. Docker inserts its own rules into the DOCKER-USER chain, which the
# kernel consults before ufw's, so a published port is reachable whatever ufw
# says. That is not a hole here because the only published ports are the edge's
# 80 and 443 -- which is exactly why docker-compose.prod.yml publishes nothing
# else, and why that file, not this firewall, is the first line of defence.

# --- unattended upgrades ----------------------------------------------------
# One box, one owner, and nobody watching a CVE feed. Automatic security
# updates are the only realistic patching story, and the tradeoff -- an
# unattended upgrade can restart a service or the box -- is exactly what the
# systemd unit above and the containers' restart policies are for.

step "unattended security upgrades"
apt-get install --yes --no-install-recommends unattended-upgrades >/dev/null
cat >/etc/apt/apt.conf.d/20auto-upgrades <<'AUTOUPGRADE'
// Managed by infra/host/bootstrap.sh.
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
AUTOUPGRADE
systemctl enable --now unattended-upgrades.service >/dev/null 2>&1 || true
note "security updates apply automatically"

# --- swap -------------------------------------------------------------------
# 4 GB, no swap, and a JVM plus two Postgres servers plus a model sidecar. The
# peak is not steady state: it is a deploy, when the release and materialize
# jobs run while the previous release's containers are still up. Swap turns
# that spike into a slow minute instead of an OOM kill. swappiness stays low so
# the kernel keeps using it as a relief valve rather than as memory.

step "swap"
if swapon --show --noheadings | grep -q .; then
	note "swap already active: $(swapon --show=NAME,SIZE --noheadings | tr '\n' ' ')"
else
	fallocate -l 2G /swapfile
	chmod 0600 /swapfile
	mkswap /swapfile >/dev/null
	swapon /swapfile
	grep -qxF '/swapfile none swap sw 0 0' /etc/fstab ||
		printf '/swapfile none swap sw 0 0\n' >>/etc/fstab
	note "created a 2G swapfile"
fi
printf 'vm.swappiness=10\n' >/etc/sysctl.d/60-movielens-swappiness.conf
sysctl --quiet --load /etc/sysctl.d/60-movielens-swappiness.conf

# --- Docker -----------------------------------------------------------------
# From Docker's own apt repository, not Ubuntu's docker.io: the compose v2
# plugin, buildx and current engine releases only come from there, and every
# compose invocation in this repository is `docker compose`, not the v1 script.

step "Docker engine and compose plugin"
apt-get install --yes --no-install-recommends ca-certificates curl gnupg >/dev/null
install -m 0755 -d /etc/apt/keyrings
if [ ! -s /etc/apt/keyrings/docker.asc ]; then
	curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
	chmod a+r /etc/apt/keyrings/docker.asc
fi
printf 'deb [arch=%s signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu %s stable\n' \
	"$(dpkg --print-architecture)" "$VERSION_CODENAME" >/etc/apt/sources.list.d/docker.list
apt-get update >/dev/null
apt-get install --yes --no-install-recommends \
	docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin >/dev/null
note "$(docker --version), $(docker compose version)"

step "Docker daemon configuration"
# Log rotation, and that is the whole file. Container stdout is the only log
# this system keeps -- there is no log shipper on this box -- and the default
# json-file driver has no rotation at all, so a chatty container fills 40 GB
# and Postgres starts refusing writes. 20m x 5 per container is ~100 MB
# worst-case each and days of history at this traffic.
#
# It applies to containers CREATED after the daemon reads it, so a deploy is
# what actually puts it into effect for the services.
install -d -m 0755 /etc/docker
if cmp -s "$HOST_DIR/docker-daemon.json" /etc/docker/daemon.json; then
	note "/etc/docker/daemon.json already current"
else
	install -m 0644 "$HOST_DIR/docker-daemon.json" /etc/docker/daemon.json
	systemctl restart docker
	docker_restarted=yes
	note "installed /etc/docker/daemon.json and restarted the daemon"
fi

if id -nG "$DEPLOY_USER" | tr ' ' '\n' | grep -qx docker; then
	note "$DEPLOY_USER is already in the docker group"
else
	usermod -aG docker "$DEPLOY_USER"
	note "added $DEPLOY_USER to the docker group"
fi

# --- the checkout -----------------------------------------------------------

step "checkout ownership"
if [ -d "$APP_DIR" ]; then
	chown -R "$DEPLOY_USER:$DEPLOY_USER" "$APP_DIR"
	note "$APP_DIR owned by $DEPLOY_USER"
	# git refuses to operate on a repository owned by another user, and the
	# deploy runs `git fetch` and `git checkout --detach` as this user.
	su - "$DEPLOY_USER" -c "git config --global --get-all safe.directory | grep -qxF '$APP_DIR'" ||
		su - "$DEPLOY_USER" -c "git config --global --add safe.directory '$APP_DIR'"
else
	note "$APP_DIR does not exist yet -- clone the repository there before deploying"
fi

if [ -f "$APP_DIR/.env.prod" ]; then
	chown "$DEPLOY_USER:$DEPLOY_USER" "$APP_DIR/.env.prod"
	chmod 0600 "$APP_DIR/.env.prod"
	note ".env.prod present, 0600, owned by $DEPLOY_USER"
else
	note ".env.prod is missing -- copy infra/deploy/production.env.example and fill it in"
fi

# --- systemd units ----------------------------------------------------------

step "systemd units"
for unit in movielens.service movielens-backup.service movielens-backup.timer \
	movielens-prune.service movielens-prune.timer; do
	install -m 0644 "$HOST_DIR/$unit" "/etc/systemd/system/$unit"
done
systemctl daemon-reload

# The timers are enabled and started: they are safe with no release deployed
# (the backup job would simply fail against a stopped database, loudly, which
# is the correct signal). movielens.service is enabled so the stack comes back
# after a reboot, but only started when there is something to start -- an
# `up -d` with no .env.prod fails, and a unit that has failed once at bootstrap
# is a misleading thing to leave behind.
systemctl enable movielens.service >/dev/null
systemctl enable --now movielens-backup.timer movielens-prune.timer >/dev/null
note "movielens.service enabled; backup and prune timers enabled and started"

if [ -f "$APP_DIR/.env.prod" ] && [ -f "$APP_DIR/docker-compose.prod.yml" ]; then
	systemctl start movielens.service || note "movielens.service did not start; check journalctl -u movielens"
fi

# --- summary ----------------------------------------------------------------

cat <<SUMMARY

== done
   docker daemon restarted this run: $docker_restarted

   Next, in order:
     1. point both public hostnames at this box (A records) -- the edge's
        certificate request fails without them
     2. cp $APP_DIR/infra/deploy/production.env.example $APP_DIR/.env.prod
        and replace every REPLACE_ME__ value, both hostnames and ACME_EMAIL
     3. chmod 0600 $APP_DIR/.env.prod && chown $DEPLOY_USER $APP_DIR/.env.prod
     4. deploy: sudo -u $DEPLOY_USER $APP_DIR/infra/deploy/deploy.sh <sha>
        (or let CI do it -- the private half of the deploy key goes into the
        production environment's DEPLOY_SSH_KEY secret)
SUMMARY
