#!/usr/bin/env bash
#
# Provision the production Keycloak realms, clients and accounts (ADR 0007:
# one realm per tenant).
#
# This runs as its own one-shot job against an already-running server rather
# than as `--import-realm` at server start. An import never overwrites a realm
# that already exists in the database, so once the first boot has happened,
# editing a template would look applied and be nothing of the sort. Everything
# below reads before it writes: a second run makes no change, and a template
# edit is picked up the next time the job runs.
#
# Realms `demo` and `default` mirror the two rows migration 0002 seeds into
# public.tenants. Provisioning a tenant means creating both the realm and the
# registry row — a verified realm with no matching row is rejected at the
# authenticated boundary (src/auth/middleware.py), so either half alone fails
# closed.
#
# Templates live in realms/prod/ and are inert data — no users, no secrets, and
# one ${APP_ORIGIN} placeholder for the redirect URIs and web origins. They are
# split the way the admin API is: a realm PUT ignores nested clients and a
# client PUT ignores nested protocol mappers, so <realm>-realm.json carries
# realm settings, clients/ carries one file per client, and the audience mapper
# is declared once and attached to every client. Splitting them is what lets
# this script reconcile an existing realm from the same files it created it
# with, instead of only ever applying them once.
#
# Required environment:
#   APP_ORIGIN               public origin of the web app, e.g. https://app.example.com.
#                            Substituted into the redirect URIs and web origins.
#   KEYCLOAK_ADMIN           bootstrap admin username (KC_BOOTSTRAP_ADMIN_USERNAME is
#   KEYCLOAK_ADMIN_PASSWORD  also accepted; Keycloak 26 renamed the pair)
#   KC_API_CLIENT_SECRET     secret pushed onto movielens-api in both realms
#   KC_VERIFY_CLIENT_SECRET  secret pushed onto movielens-verify in both realms
#   WALKTHROUGH_PASSWORD     the published portfolio account (realm demo)
#   VERIFY_PASSWORD          the release verification account (realm demo)
#   ISOLATION_PASSWORD       the cross-tenant canary account (realm default)
#   KC_HUMAN_ADMIN_USERNAME  named master-realm admin that outlives the bootstrap
#   KC_HUMAN_ADMIN_PASSWORD  account, which the runbook disables straight after
#
# Optional:
#   KEYCLOAK_URL             server to provision (default http://localhost:8080)
#   KC_RESET_PASSWORDS       "true" re-sets the account passwords on accounts that
#                            already exist. Off by default, so a re-run changes
#                            nothing; turn it on deliberately to rotate.
#   ALLOW_INSECURE_APP_ORIGIN "true" accepts a non-https APP_ORIGIN (rehearsals only)
#   KEYCLOAK_WAIT_SECONDS    how long to wait for the server to accept an admin
#                            login before giving up (default 180)
#   KCADM_CONFIG             where the admin session is cached (default /tmp/kcadm.config)
#   REALM_TEMPLATE_DIR       template root (default: realms/prod next to this script)
#
# Secrets arrive as environment variables and are generated by the operator; we
# push them rather than reading them back, so the loop closes without a human
# copying a value out of the admin console.
#
# Prints PROVISION-OK as its final line. Railway shows a cleanly exited job as
# stopped, so the deploy workflow greps for that sentinel rather than trusting
# the deployment state.

set -euo pipefail
umask 077

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE_DIR="${REALM_TEMPLATE_DIR:-${SCRIPT_DIR}/realms/prod}"
KCADM="${KCADM:-/opt/keycloak/bin/kcadm.sh}"
KCADM_CONFIG="${KCADM_CONFIG:-/tmp/kcadm.config}"
KEYCLOAK_URL="${KEYCLOAK_URL:-http://localhost:8080}"
KEYCLOAK_WAIT_SECONDS="${KEYCLOAK_WAIT_SECONDS:-180}"
KC_RESET_PASSWORDS="${KC_RESET_PASSWORDS:-false}"

# The one mapper that makes the whole thing work: without it a browser token
# carries no aud=movielens-api and the API rejects every request.
AUDIENCE_MAPPER_NAME="movielens-api-audience"

# Realm roles. `demo-impersonator` is the gate on selecting a demo persona
# (RequestPrincipal.can_access_demo_personas); `user` is ordinary membership.
# The role exists in both realms and is granted only in `demo`, which is what
# leaves the `default` realm's account 403 across the product surface.
ROLE_USER="user"
ROLE_IMPERSONATOR="demo-impersonator"

log() { printf 'provision: %s\n' "$*"; }
fail() { printf 'provision: %s\n' "$*" >&2; exit 1; }

# kcadm reads its session from a config file. We pin the path because the
# default lives under $HOME, which is not reliably writable in a job container.
# `config credentials` takes the flag in a different position, so it is called
# directly rather than through this wrapper.
kc() {
  local command="$1"
  shift
  "$KCADM" "$command" --config "$KCADM_CONFIG" "$@"
}

# Reports every missing variable at once: a job that fails eight times in a row,
# one variable per run, is a bad way to learn what it needed.
require_environment() {
  local missing="" name
  for name in "$@"; do
    if [ -z "${!name:-}" ]; then
      missing="${missing} ${name}"
    fi
  done
  if [ -n "$missing" ]; then
    fail "missing required environment:${missing}"
  fi
}

# Replace the single ${APP_ORIGIN} placeholder the templates carry. Rendering
# happens into a temporary directory so the templates stay inert data that can
# be diffed against a realm export.
render_template() {
  local source="$1" destination="$2" content
  [ -f "$source" ] || fail "template not found: $source"
  content="$(cat "$source")"
  printf '%s' "${content//'${APP_ORIGIN}'/$APP_ORIGIN}" >"$destination"
  if grep -q '\${' "$destination"; then
    fail "unresolved placeholder left in $source"
  fi
  assert_descriptions_fit "$source" "$destination"
}

# Keycloak stores a client's description in a varchar(255) and the admin API
# does not check the length: the write reaches Postgres, fails there, and kcadm
# reports `[unknown_error]` while the only readable cause -- "value too long for
# type character varying(255)" -- is in the server's own log, which on a managed
# platform is a different pane. Provisioning then aborts partway through, having
# created the realm and its roles but no clients, so the first symptom is every
# browser token being rejected for want of an audience mapper. Check it here,
# where the message can name the file and the number.
assert_descriptions_fit() {
  local source="$1" rendered="$2" value
  while IFS= read -r value; do
    [ -n "$value" ] || continue
    if [ "${#value}" -gt 255 ]; then
      fail "$source: \"description\" is ${#value} characters; Keycloak's column holds 255 and the overflow surfaces only as [unknown_error]"
    fi
  done <<EOF
$(sed -n 's/^[[:space:]]*"description"[[:space:]]*:[[:space:]]*"\(.*\)",\{0,1\}[[:space:]]*$/\1/p' "$rendered")
EOF
}

# Every lookup collects kcadm's output before matching on it. Piping straight
# into `grep -q` lets grep close the pipe on the first hit, which under
# `pipefail` reports the whole lookup as failed and would have us re-create
# something that is already there.
client_uuid() {
  local found
  found="$(kc get clients -r "$1" -q "clientId=$2" --fields id --format csv --noquotes 2>/dev/null || true)"
  printf '%s' "$found" | head -n 1 | tr -d '\r"'
}

user_uuid() {
  local found
  found="$(kc get users -r "$1" -q "username=$2" -q exact=true --fields id --format csv --noquotes 2>/dev/null || true)"
  printf '%s' "$found" | head -n 1 | tr -d '\r"'
}

# user_field <realm> <username> <attribute>. Empty when the attribute is unset,
# which is what makes the email reconciliation below a no-op on a second run.
user_field() {
  local found
  found="$(kc get users -r "$1" -q "username=$2" -q exact=true --fields "$3" --format csv --noquotes 2>/dev/null || true)"
  printf '%s' "$found" | head -n 1 | tr -d '\r"'
}

mapper_present() {
  local names
  names="$(kc get "clients/$2/protocol-mappers/models" -r "$1" --fields name --format csv --noquotes 2>/dev/null || true)"
  grep -Fxq "$AUDIENCE_MAPPER_NAME" <<<"$names"
}

user_has_role() {
  local granted
  granted="$(kc get-roles -r "$1" --uusername "$2" --fields name --format csv --noquotes 2>/dev/null || true)"
  grep -Fxq "$3" <<<"$granted"
}

ensure_realm() {
  local realm="$1" rendered="${WORK_DIR}/${1}-realm.json"
  render_template "${TEMPLATE_DIR}/${realm}-realm.json" "$rendered"
  if kc get "realms/${realm}" >/dev/null 2>&1; then
    kc update "realms/${realm}" -f "$rendered" >/dev/null
    log "realm ${realm}: settings reconciled"
  else
    kc create realms -f "$rendered" >/dev/null
    log "realm ${realm}: created"
  fi
}

ensure_realm_role() {
  local realm="$1" name="$2" description="$3"
  if kc get "roles/${name}" -r "$realm" >/dev/null 2>&1; then
    return
  fi
  kc create roles -r "$realm" -s "name=${name}" -s "description=${description}" >/dev/null
  log "realm ${realm}: role ${name} created"
}

# A realm PUT ignores nested clients, and a client PUT ignores nested protocol
# mappers, so each is reconciled on its own endpoint.
ensure_client() {
  local realm="$1" client_id="$2" secret="${3:-}"
  local rendered="${WORK_DIR}/${realm}-${client_id}.json" uuid
  render_template "${TEMPLATE_DIR}/clients/${client_id}.json" "$rendered"

  uuid="$(client_uuid "$realm" "$client_id")"
  if [ -z "$uuid" ]; then
    kc create clients -r "$realm" -f "$rendered" >/dev/null
    uuid="$(client_uuid "$realm" "$client_id")"
    [ -n "$uuid" ] || fail "realm ${realm}: client ${client_id} was not created"
    log "realm ${realm}: client ${client_id} created"
  else
    kc update "clients/${uuid}" -r "$realm" -f "$rendered" >/dev/null
    log "realm ${realm}: client ${client_id} reconciled"
  fi

  if [ -n "$secret" ]; then
    kc update "clients/${uuid}" -r "$realm" -s "secret=${secret}" >/dev/null
    log "realm ${realm}: client ${client_id} secret set from the environment"
  fi

  if ! mapper_present "$realm" "$uuid"; then
    kc create "clients/${uuid}/protocol-mappers/models" -r "$realm" \
      -f "${WORK_DIR}/audience-mapper.json" >/dev/null
    log "realm ${realm}: client ${client_id} audience mapper created"
  fi
}

# ensure_user <realm> <username> <first> <last> <email> <password> [role...]
#
# The email is not decoration. Keycloak 25 always runs the declarative user
# profile, whose default marks email, firstName and lastName
# `required: {roles: ["user"]}` -- required in the *user* context, which
# includes authenticating. An account the admin API created without one is
# accepted at creation, reports an empty `requiredActions`, looks completely
# healthy in the console, and then fails every direct grant with
#
#   {"error":"invalid_grant","error_description":"Account is not fully set up"}
#
# firstName and lastName were always set here; email was not, so every token
# this deployment's automation asks for -- the verify job, the cross-tenant
# canary, the load canary -- and the browser sign-in for `walkthrough` failed
# identically until R-7's rehearsal ran the first real password grant.
# Addresses use the RFC 2606 `.invalid` TLD: syntactically valid, reserved, and
# guaranteed never to resolve, because nothing here should be able to send mail.
ensure_user() {
  local realm="$1" username="$2" first="$3" last="$4" email="$5" password="$6"
  shift 6
  local roles=("$@")
  local uuid created=0 role

  # Six positional arguments, and the password sits directly after the address.
  # Drop one and every later argument shifts left, which puts the password into
  # the email attribute -- Keycloak answers `error-invalid-email` and the value
  # it rejected is a live credential. Check the shape, and deliberately do not
  # echo the value that failed.
  if [ -n "$email" ] && [[ "$email" != ?*@?*.?* ]]; then
    fail "ensure_user ${realm}/${username}: argument 5 is not an email address. Check the argument order -- the value is withheld here because a shifted argument in this position is a password"
  fi

  local create_args=(-s "username=${username}" -s "enabled=true")
  if [ -n "$first" ]; then create_args+=(-s "firstName=${first}"); fi
  if [ -n "$last" ]; then create_args+=(-s "lastName=${last}"); fi
  # emailVerified rides with the address: VERIFY_EMAIL is an enabled action
  # provider in both realms and there is no mail server to complete it with.
  if [ -n "$email" ]; then
    create_args+=(-s "email=${email}" -s "emailVerified=true")
  fi

  uuid="$(user_uuid "$realm" "$username")"
  if [ -z "$uuid" ]; then
    kc create users -r "$realm" "${create_args[@]}" >/dev/null
    uuid="$(user_uuid "$realm" "$username")"
    [ -n "$uuid" ] || fail "realm ${realm}: user ${username} was not created"
    created=1
    log "realm ${realm}: user ${username} created"
  elif [ -n "$email" ] && [ "$(user_field "$realm" "$username" email)" != "$email" ]; then
    # Repairs an account provisioned before the address was set, so a
    # deployment already carrying the broken shape heals on the next run
    # instead of needing a console visit. A correct account skips this.
    kc update "users/${uuid}" -r "$realm" -s "email=${email}" -s "emailVerified=true" >/dev/null
    log "realm ${realm}: user ${username} email set"
  fi

  for role in "${roles[@]}"; do
    if user_has_role "$realm" "$username" "$role"; then
      continue
    fi
    kc add-roles -r "$realm" --uusername "$username" --rolename "$role" >/dev/null
    log "realm ${realm}: user ${username} granted ${role}"
  done

  # Re-setting a password rewrites the stored credential, so an untouched
  # account keeps the one it has unless a rotation is asked for explicitly.
  if [ "$created" -eq 1 ] || [ "$KC_RESET_PASSWORDS" = "true" ]; then
    kc set-password -r "$realm" --username "$username" --new-password "$password" >/dev/null
    log "realm ${realm}: user ${username} password set"
  fi
}

assert_realm_flag() {
  local realm="$1" field="$2" expected="$3" observed
  # `--fields` and `-c` are mutually exclusive: kcadm applies both field
  # filtering and CSV rendering to the parsed response, and -c makes it hand
  # back the raw compressed body instead, so the pair fails with "Cannot create
  # CSV nor filter returned fields because the response is compressed" and takes
  # the whole run down after every realm, client and account has already been
  # written. The csv form is what the other four lookups in this file use.
  observed="$(kc get "realms/${realm}" --fields "$field" --format csv --noquotes | tr -d ' \n\t\r')"
  if [ "$observed" != "$expected" ]; then
    fail "realm ${realm}: ${field} reads '${observed}', expected '${expected}'"
  fi
}

assert_audience_mapper() {
  local realm="$1" client_id="$2" uuid
  uuid="$(client_uuid "$realm" "$client_id")"
  [ -n "$uuid" ] || fail "realm ${realm}: client ${client_id} is missing"
  if ! mapper_present "$realm" "$uuid"; then
    fail "realm ${realm}: client ${client_id} has no ${AUDIENCE_MAPPER_NAME} mapper — its tokens would carry no aud=movielens-api and the API would reject every one of them"
  fi
}

require_environment \
  APP_ORIGIN \
  KC_API_CLIENT_SECRET \
  KC_VERIFY_CLIENT_SECRET \
  WALKTHROUGH_PASSWORD \
  VERIFY_PASSWORD \
  ISOLATION_PASSWORD \
  KC_HUMAN_ADMIN_USERNAME \
  KC_HUMAN_ADMIN_PASSWORD

ADMIN_USER="${KEYCLOAK_ADMIN:-${KC_BOOTSTRAP_ADMIN_USERNAME:-}}"
ADMIN_PASSWORD="${KEYCLOAK_ADMIN_PASSWORD:-${KC_BOOTSTRAP_ADMIN_PASSWORD:-}}"
[ -n "$ADMIN_USER" ] || fail "missing required environment: KEYCLOAK_ADMIN (or KC_BOOTSTRAP_ADMIN_USERNAME)"
[ -n "$ADMIN_PASSWORD" ] || fail "missing required environment: KEYCLOAK_ADMIN_PASSWORD (or KC_BOOTSTRAP_ADMIN_PASSWORD)"

APP_ORIGIN="${APP_ORIGIN%/}"
case "$APP_ORIGIN" in
  https://*) ;;
  *)
    if [ "${ALLOW_INSECURE_APP_ORIGIN:-false}" != "true" ]; then
      fail "APP_ORIGIN must be an https origin (got '${APP_ORIGIN}'); set ALLOW_INSECURE_APP_ORIGIN=true for a local rehearsal"
    fi
    log "WARNING: provisioning redirect URIs for the non-https origin ${APP_ORIGIN}"
    ;;
esac

[ -d "$TEMPLATE_DIR" ] || fail "template directory not found: ${TEMPLATE_DIR}"
[ -x "$KCADM" ] || fail "kcadm not found or not executable: ${KCADM}"

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

log "provisioning ${KEYCLOAK_URL} for app origin ${APP_ORIGIN}"

# The job may start before the server is accepting connections; the login
# doubles as the readiness probe because the image carries no HTTP client.
deadline=$(( $(date +%s) + KEYCLOAK_WAIT_SECONDS ))
until "$KCADM" config credentials --config "$KCADM_CONFIG" \
  --server "$KEYCLOAK_URL" --realm master \
  --user "$ADMIN_USER" --password "$ADMIN_PASSWORD" >/dev/null 2>&1; do
  if [ "$(date +%s)" -ge "$deadline" ]; then
    fail "could not authenticate against ${KEYCLOAK_URL} as ${ADMIN_USER} within ${KEYCLOAK_WAIT_SECONDS}s"
  fi
  sleep 5
done
log "authenticated as ${ADMIN_USER}"

render_template "${TEMPLATE_DIR}/clients/audience-mapper.json" "${WORK_DIR}/audience-mapper.json"

for realm in demo default; do
  ensure_realm "$realm"
  ensure_realm_role "$realm" "$ROLE_USER" "Ordinary API user for the ${realm} tenant"
  ensure_realm_role "$realm" "$ROLE_IMPERSONATOR" "May select synthetic MovieLens demo personas"
  ensure_client "$realm" movielens-api "$KC_API_CLIENT_SECRET"
  ensure_client "$realm" movielens-web
  ensure_client "$realm" movielens-verify "$KC_VERIFY_CLIENT_SECRET"
done

# Exactly three accounts, and the difference between them is the point:
# `walkthrough` is the published portfolio login, `verify` is known only to
# Railway and GitHub Actions, and `isolation` deliberately lacks
# demo-impersonator so the cross-tenant canary has a subject that must be
# refused across the whole product surface.
ensure_user demo walkthrough "Portfolio" "Walkthrough" walkthrough@movielens.invalid \
  "$WALKTHROUGH_PASSWORD" "$ROLE_USER" "$ROLE_IMPERSONATOR"
ensure_user demo verify "Release" "Verification" verify@movielens.invalid \
  "$VERIFY_PASSWORD" "$ROLE_USER" "$ROLE_IMPERSONATOR"
ensure_user default isolation "Isolation" "Canary" isolation@movielens.invalid \
  "$ISOLATION_PASSWORD" "$ROLE_USER"

# A named admin that survives the runbook's next step: deleting the bootstrap
# variables and disabling the account they created.
ensure_user master "$KC_HUMAN_ADMIN_USERNAME" "" "" \
  "${KC_HUMAN_ADMIN_USERNAME}@movielens.invalid" "$KC_HUMAN_ADMIN_PASSWORD" admin

for realm in demo default; do
  assert_realm_flag "$realm" registrationAllowed false
  assert_realm_flag "$realm" bruteForceProtected true
  assert_audience_mapper "$realm" movielens-api
  assert_audience_mapper "$realm" movielens-web
  assert_audience_mapper "$realm" movielens-verify
done
log "realm invariants asserted: registration closed, brute-force protection on, audience mapper on every client"

echo "PROVISION-OK"
