"""Guard the production Keycloak image, realm templates and provisioning script.

None of this can be proved by booting the app: a dropped audience mapper, a
realm template that smuggles a password in, or a provisioning step that creates
without reading first all present as a working deploy right up until the moment
they don't. A missing ``oidc-audience-mapper`` in particular has no partial
failure mode — every browser token stops carrying ``aud=movielens-api`` and the
API rejects all of them (``src/auth/middleware.py``).

So these are structural assertions over the files themselves, in the same
spirit as the frontend's fixture lockout: read the artifact, not a mock of it.
The live round trip — sign in over https, provision twice, diff the realm — is
the deployment rehearsal's job.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

import pytest

_REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
_KEYCLOAK_DIR = _REPOSITORY_ROOT / "infra" / "keycloak"
_TEMPLATE_DIR = _KEYCLOAK_DIR / "realms" / "prod"
_CLIENT_DIR = _TEMPLATE_DIR / "clients"
_PROVISION = _KEYCLOAK_DIR / "provision.sh"
_DOCKERFILE = _KEYCLOAK_DIR / "Dockerfile"

_REALMS = ("demo", "default")
_CLIENTS = ("movielens-api", "movielens-web", "movielens-verify")
_CALLBACK = "${APP_ORIGIN}/api/auth/callback/keycloak"

# Reads that make a create idempotent. Every mutating kcadm call below one of
# these is a reconcile; every mutating call without one is a second-run failure.
_LOOKUPS = ("kc get ", "client_uuid", "user_uuid", "mapper_present", "user_has_role")
_MUTATIONS = re.compile(r"\bkc (create|add-roles)\b")
_FUNCTION_HEADER = re.compile(r"^(?P<name>[a-z_]+)\(\) \{$")


def _load(path: Path) -> dict[str, Any]:
    parsed: dict[str, Any] = json.loads(path.read_text())
    return parsed


def _script() -> str:
    return _PROVISION.read_text()


def _function_bodies(script: str) -> dict[str, list[str]]:
    """Split the script into ``name() { ... }`` blocks, ignoring nesting-free bodies."""
    bodies: dict[str, list[str]] = {}
    name: str | None = None
    body: list[str] = []
    for line in script.splitlines():
        if name is None:
            header = _FUNCTION_HEADER.match(line)
            if header:
                name = header.group("name")
                body = []
            continue
        if line == "}":
            bodies[name] = body
            name = None
            continue
        body.append(line)
    return bodies


def _top_level_lines(script: str) -> list[str]:
    inside = False
    lines: list[str] = []
    for line in script.splitlines():
        if not inside and _FUNCTION_HEADER.match(line):
            inside = True
            continue
        if inside:
            if line == "}":
                inside = False
            continue
        lines.append(line)
    return lines


@pytest.mark.parametrize("realm", _REALMS)
def test_realm_templates_preserve_the_seeded_security_settings(realm: str) -> None:
    template = _load(_TEMPLATE_DIR / f"{realm}-realm.json")

    assert template["realm"] == realm
    assert template["enabled"] is True
    assert template["registrationAllowed"] is False
    assert template["resetPasswordAllowed"] is False
    assert template["editUsernameAllowed"] is False
    assert template["duplicateEmailsAllowed"] is False
    assert template["bruteForceProtected"] is True
    assert template["accessTokenLifespan"] == 300

    # "external" rather than "all": TLS terminates at the edge, and the BFF's
    # token exchange and refresh are deliberately routed to the internal origin
    # over plain http (web/lib/auth-token.ts). "all" would refuse those.
    assert template["sslRequired"] == "external"


@pytest.mark.parametrize("realm", _REALMS)
def test_realm_templates_carry_no_accounts(realm: str) -> None:
    template = _load(_TEMPLATE_DIR / f"{realm}-realm.json")

    assert "users" not in template
    assert "credentials" not in json.dumps(template)


@pytest.mark.parametrize("client", _CLIENTS)
def test_client_templates_carry_no_secret(client: str) -> None:
    template = _load(_CLIENT_DIR / f"{client}.json")

    # Secrets are generated by the operator and pushed by provision.sh, so the
    # templates stay publishable in a public repository.
    assert "secret" not in template


def test_browser_clients_are_pinned_to_the_app_origin() -> None:
    for client in ("movielens-api", "movielens-web"):
        template = _load(_CLIENT_DIR / f"{client}.json")
        assert template["redirectUris"] == [_CALLBACK]
        assert template["webOrigins"] == ["${APP_ORIGIN}"]

    for template_path in sorted(_CLIENT_DIR.glob("*.json")):
        assert "*" not in template_path.read_text()


def test_api_client_issues_no_tokens_of_its_own() -> None:
    template = _load(_CLIENT_DIR / "movielens-api.json")

    # It is the audience, nothing else: no password grant and no service
    # account means no path to a token whose azp is the trusted service client.
    assert template["publicClient"] is False
    assert template["directAccessGrantsEnabled"] is False
    assert template["serviceAccountsEnabled"] is False


def test_verify_client_holds_the_password_grant_alone() -> None:
    template = _load(_CLIENT_DIR / "movielens-verify.json")

    assert template["publicClient"] is False
    assert template["directAccessGrantsEnabled"] is True
    assert template["serviceAccountsEnabled"] is False
    assert template["standardFlowEnabled"] is False
    assert template["redirectUris"] == []


def test_web_client_stays_public_with_pkce() -> None:
    template = _load(_CLIENT_DIR / "movielens-web.json")

    assert template["publicClient"] is True
    assert template["directAccessGrantsEnabled"] is False
    assert template["attributes"]["pkce.code.challenge.method"] == "S256"


def test_audience_mapper_injects_the_api_audience_into_access_tokens() -> None:
    mapper = _load(_CLIENT_DIR / "audience-mapper.json")

    assert mapper["protocolMapper"] == "oidc-audience-mapper"
    assert mapper["config"]["included.client.audience"] == "movielens-api"
    assert mapper["config"]["access.token.claim"] == "true"
    assert mapper["config"]["id.token.claim"] == "false"


def test_templates_carry_only_the_placeholder_provisioning_can_render() -> None:
    for template_path in sorted(_TEMPLATE_DIR.rglob("*.json")):
        placeholders = set(re.findall(r"\$\{[^}]*\}", template_path.read_text()))
        assert placeholders <= {"${APP_ORIGIN}"}, template_path


def test_every_mutating_kcadm_call_reads_before_it_writes() -> None:
    script = _script()
    bodies = _function_bodies(script)

    mutating = {
        name: body for name, body in bodies.items() if any(_MUTATIONS.search(x) for x in body)
    }
    assert set(mutating) == {"ensure_realm", "ensure_realm_role", "ensure_client", "ensure_user"}

    for name, body in mutating.items():
        for index, line in enumerate(body):
            if not _MUTATIONS.search(line):
                continue
            preceding = body[:index]
            assert any(
                lookup in earlier for earlier in preceding for lookup in _LOOKUPS
            ), f"{name} mutates on line {index + 1} without looking the resource up first"

    # A create outside a guarded function would be a create on every run.
    assert not [line for line in _top_level_lines(script) if _MUTATIONS.search(line)]


def test_accounts_grant_the_impersonator_role_only_where_it_belongs() -> None:
    script = _script().replace("\\\n", " ")
    calls = {
        f"{match.group('realm')}/{match.group('user')}": match.group("rest")
        for match in re.finditer(
            r"^ensure_user (?P<realm>\S+) (?P<user>\S+) (?P<rest>.*)$", script, re.MULTILINE
        )
    }

    assert set(calls) == {
        "demo/walkthrough",
        "demo/verify",
        "default/isolation",
        'master/"$KC_HUMAN_ADMIN_USERNAME"',
    }
    assert "$ROLE_IMPERSONATOR" in calls["demo/walkthrough"]
    assert "$ROLE_IMPERSONATOR" in calls["demo/verify"]
    # The cross-tenant canary needs a subject that is refused everywhere.
    assert "$ROLE_IMPERSONATOR" not in calls["default/isolation"]
    assert "$ROLE_USER" in calls["default/isolation"]


def test_provisioning_asserts_the_audience_mapper_before_reporting_success() -> None:
    script = _script()

    for client in _CLIENTS:
        assert f'assert_audience_mapper "$realm" {client}' in script
    assert script.rstrip().endswith('echo "PROVISION-OK"')
    assert "set -euo pipefail" in script


def test_image_starts_optimized_and_never_imports_realms() -> None:
    # Instructions only — the comments above them discuss both of the things
    # the image deliberately does not do.
    instructions = "\n".join(
        line for line in _DOCKERFILE.read_text().splitlines() if not line.lstrip().startswith("#")
    )

    assert "kc.sh build --db=postgres --health-enabled=true" in instructions
    assert 'CMD ["start", "--optimized"]' in instructions
    # An import silently skips a realm that already exists, which is exactly
    # the failure this deployment is built to avoid.
    assert "--import-realm" not in instructions
    assert "start-dev" not in instructions
